[workspace]
members = ["katherine-fundraising-contract", "test-meta-pool", "test-p-token"]

[profile.release]
codegen-units=1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
